apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app 
  labels:
    app: my-app 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app 
    spec:
      containers:
      - name: my-app 
        image: nginx:alpine
        volumeMounts:
        - name: config-mp
          mountPath: /etc/nginx/
        ports:
        - containerPort: 7777
      volumes:
      - name: config-mp
        configMap:
          name: config-mp
