apiVersion: v1
kind: Service
metadata:
  labels:
    app: my-app-2
  name: my-app-svc
spec:
  ports:
  - port: 7777
    protocol: TCP
    targetPort: 7777
  selector:
    app: my-app-2
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}

