apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-2
  labels:
    app: my-app-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app-2
  template:
    metadata:
      labels:
        app: my-app-2
    spec:
      containers:
      - name: simple-express
        image: kuchda6/simple-express
        ports:
        - containerPort: 7777
        livenessProbe:
          httpGet:
            path: /health
            port: 7777
          initialDelaySeconds: 3
          periodSeconds: 3

